# Generated by Django 4.1.6 on 2023-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID_EMPLEADO', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=30)),
                ('APELLIDOS', models.CharField(max_length=60)),
                ('UBICACION', models.CharField(max_length=60)),
                ('PUESTO', models.CharField(max_length=30)),
                ('NUMERO_TELEFONO', models.CharField(max_length=20)),
                ('EXTENSION', models.CharField(max_length=10)),
            ],
        ),
    ]
